version: "3"
services:
  adminer:
      image: adminer
      container_name: adminer_app
      restart: always
      ports:
        - "8085:8080"

  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vr-projeto
    ports: 
      - "5432:5432"
    volumes:
      - .pg-data:/var/lib/postgresql/data
      - ./postgres_custom:/etc/postgresql  

# Adicionando o volume persistente para o banco de dados
volumes:
  pg-data:
